language: go

go:
  - 1.6.2

sudo: required

env:
  global:
  - PGPORT=5432
  - PGHOST=localhost

services:
  - docker

install:
 - go get github.com/mattn/goveralls
 - make setup

before_script:
  - sleep 10

script:
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile _build/test-coverage-all.out -service=travis-ci
  - make cross
  - ./push_to_docker.sh
  #- /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ] && curl -H POST $TEST_FARM_URL'
