healthcheck:
  workingText: WORKING

mongo:
  host: mongo
  port: 27017
  db: donations

redis:
  url: redis://localhost:6379/0
  maxIdle: 3
  idleTimeoutSeconds: 240

sentry:
  url: ""

api:
  donationRequestCooldownHours: 8
  maxReadBufferSize: 80240
  basicAuth:
    user: ""
    pass: ""
