healthcheck:
  workingText: WORKING

mongo:
  host: localhost
  port: 9999
  db: donations

redis:
  url: redis://localhost:6379/0
  maxIdle: 3
  idleTimeoutSeconds: 240

sentry:
  url: ""

api:
  donationRequestCooldownHours: 8
  maxReadBufferSize: 80240
  basicAuth:
    user: ""
    pass: ""
