healthcheck:
  workingText: WORKING

mongo:
  host: localhost
  port: 9999
  db: donations-perf

redis:
  url: redis://localhost:6379/1
  maxIdle: 3
  idleTimeoutSeconds: 240

sentry:
  url: ""

api:
  maxReadBufferSize: 80240
  authenticateProvider: false
  basicAuth:
    user: ""
    pass: ""
  providers:
    gamecenter:
      timeout: 600
