healthcheck:
  workingText: WORKING

mongo:
  host: localhost
  port: 9999
  db: donations-test

redis:
  url: redis://localhost:9998/1
  maxIdle: 3
  idleTimeoutSeconds: 240

sentry:
  url: ""

api:
  maxReadBufferSize: 80240
  basicAuth:
    user: ""
    pass: ""
